version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
